catalog/urls.py
from django.urls import path
from .views import (
    index,
    LiteraryFormatListView,
    LiteraryFormatCreateView,
    LiteraryFormatUpdateView,
    LiteraryFormatDeleteView,
    BookListView,
    BookCreateView,
    BookDetailView,
    BookUpdateView,
    AuthorListView,
    AuthorDetailView
)

app_name = 'catalog'

urlpatterns = [
    path("", index, name="index"),
    path("books/", BookListView.as_view(), name="book_list"),
    path("books/create/", BookCreateView.as_view(), name="book_create"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book_detail"),
    path("books/<int:pk>/update/", BookUpdateView.as_view(), name="book_update"),
    path("authors/", AuthorListView.as_view(), name="author_list"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author_detail"),
    path("literary-formats/", LiteraryFormatListView.as_view(), name="literary_format_list"),
    path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name="literary_format_create"),
    path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name="literary_format_update"),
    path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name="literary_format_delete"),
]

doc/005_Samples/005_Samples/example_1/django_courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("lesson_1/", include("lesson_1.urls")),
    path("lesson_2/", include("lesson_2.urls")),
    path("lesson_3/", include("lesson_3.urls")),
    path("lesson_5/", include("lesson_5.urls")),
]

doc/006_Samples/006_Samples/example_1/django_courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("lesson_1/", include("lesson_1.urls")),
    path("lesson_2/", include("lesson_2.urls")),
    path("lesson_3/", include("lesson_3.urls")),
    path("lesson_5/", include("lesson_5.urls")),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("__debug__/", include("debug_toolbar.urls")),
    # path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls", namespace="user")),
    path("api/v1/catalog/", include("catalog.urls_api", namespace="catalog_api")),
    path("oauth/", include("social_django.urls", namespace="social")),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
]

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
    {% endif %}
    <li class="page-item active"><span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  {% if user.is_authenticated %}
    <li><strong>User: {{ user.username }}</strong></li>
    <li>
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Log Out</button>
      </form>
    </li>
    <li>
      <a href="{% url 'password_change' %}">Change password</a>
    </li>
  {% else %}
    <li>
      <a href="{% url 'login' %}">Login</a>
    </li>
    <li>
      <a href="{% url 'user:register' %}">Register</a>
    </li>
    <li>
      <a href="{% url 'password_reset' %}">Reset password</a>
    </li>
  {% endif %}
  <br>
  <li><a href="{% url 'catalog:index' %}">Home</a></li>
  <li><a href="{% url 'catalog:book_list' %}">All books</a></li>
  <li><a href="{% url 'catalog:author_list' %}">All authors</a></li>
  <li><a href="{% url 'catalog:literary_format_list' %}">All literary formats</a></li>
</ul>