catalog/urls.py
from django.urls import path
from .views import (
    index,
    LiteraryFormatListView,
    LiteraryFormatCreateView,
    LiteraryFormatUpdateView,
    LiteraryFormatDeleteView,
    BookListView,
    BookCreateView,
    BookDetailView,
    BookUpdateView,
    AuthorListView,
    AuthorDetailView
)

app_name = 'catalog'

urlpatterns = [
    path("", index, name="index"),
    path("books/", BookListView.as_view(), name="book_list"),
    path("books/create/", BookCreateView.as_view(), name="book_create"),
    path("books/<int:pk>/", BookDetailView.as_view(), name="book_detail"),
    path("books/<int:pk>/update/", BookUpdateView.as_view(), name="book_update"),
    path("authors/", AuthorListView.as_view(), name="author_list"),
    path("authors/<int:pk>/", AuthorDetailView.as_view(), name="author_detail"),
    path("literary-formats/", LiteraryFormatListView.as_view(), name="literary_format_list"),
    path("literary-formats/create/", LiteraryFormatCreateView.as_view(), name="literary_format_create"),
    path("literary-formats/<int:pk>/update/", LiteraryFormatUpdateView.as_view(), name="literary_format_update"),
    path("literary-formats/<int:pk>/delete/", LiteraryFormatDeleteView.as_view(), name="literary_format_delete"),
]

doc/005_Samples/005_Samples/example_1/django_courses/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("lesson_1/", include("lesson_1.urls")),
    path("lesson_2/", include("lesson_2.urls")),
    path("lesson_3/", include("lesson_3.urls")),
    path("lesson_5/", include("lesson_5.urls")),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls", namespace="catalog")),
    path("__debug__/", include("debug_toolbar.urls")),
    # path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls", namespace="user")),
    path("api/v1/catalog/", include("catalog.urls_api", namespace="catalog_api")),
    path("oauth/", include("social_django.urls", namespace="social")),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
]

catalog/models.py
from datetime import datetime

from django.core.validators import MinLengthValidator
from django.db import models
from django.urls import reverse


class LiteraryFormat(models.Model):
    MIN_NAME_LENGTH=3
    name = models.CharField(
        max_length=63,
        unique=True,
        validators=[
            MinLengthValidator(MIN_NAME_LENGTH)
        ]
    )
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=63)
    last_name = models.CharField(max_length=63)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.id})"

    class Meta:
        ordering = ["last_name"]

    def get_absolute_url(self):
        return reverse("catalog:author_detail", kwargs={"pk": self.pk})


class Book(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, default="Very good book.")
    format = models.ForeignKey(LiteraryFormat, on_delete=models.CASCADE, related_name="books")
    added_at = models.DateTimeField(auto_now_add=True, null=True)
    authors = models.ManyToManyField(Author, related_name="books")

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["title"]

    def get_absolute_url(self):
        return reverse("catalog:book_detail", kwargs={"pk": self.pk})

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.forms import CheckboxSelectMultiple

from catalog.models import LiteraryFormat, Book, Author


class LiteraryFormatForm(forms.ModelForm):
    # MIN_NAME_LENGTH = 3
    # name = forms.CharField(
    #     required=True,
    #     max_length=63,
    #     validators=[
    #         MinLengthValidator(MIN_NAME_LENGTH)
    #     ]
    # )
    class Meta:
        model = LiteraryFormat
        fields = ("name", "description")

    # def clean_name(self):
    #     MIN_NAME_LENGTH = 3
    #     name = self.cleaned_data["name"]
    #     if len(name) < MIN_NAME_LENGTH:
    #         raise ValidationError(f"the length of the literary format name must be more than {MIN_NAME_LENGTH} characters")
    #     return name
    #


class BookForm(forms.ModelForm):
    authors = forms.ModelMultipleChoiceField(
        queryset=Author.objects.all(),
        widget=CheckboxSelectMultiple,
        required=False,
    )
    format = forms.ModelChoiceField(
        queryset=LiteraryFormat.objects.all(),
        widget=CheckboxSelectMultiple,
    )
    class Meta:
        model = Book
        fields = "__all__"


class BookSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by title"}
        )
    )

catalog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from rest_framework.decorators import api_view
from rest_framework.generics import get_object_or_404
from rest_framework.response import Response
from rest_framework import status, generics, mixins, viewsets
from rest_framework.views import APIView

from catalog.forms import LiteraryFormatForm, BookForm, BookSearchForm
from catalog.models import Book, Author, LiteraryFormat
from catalog.serializators import LiteraryFormatSerializer, AuthorSerializer, BookSerializer


@login_required
def index(request: HttpRequest) -> HttpResponse:
    num_books = Book.objects.count()
    num_authors = Author.objects.count()
    num_literary_formats = LiteraryFormat.objects.count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1
    context = {
        "num_books": num_books,
        "num_authors": num_authors,
        "num_literary_formats": num_literary_formats,
        "num_visits": num_visits + 1
    }
    return render(request, "catalog/index.html", context=context)


class LiteraryFormatListView(LoginRequiredMixin, generic.ListView):
    model = LiteraryFormat
    template_name = "catalog/literary_format_list.html"
    context_object_name = "literary_format_list"


class LiteraryFormatCreateView(LoginRequiredMixin, generic.CreateView):
    model = LiteraryFormat
    form_class = LiteraryFormatForm
    success_url = reverse_lazy("catalog:literary_format_list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = LiteraryFormat
    fields = "__all__"
    success_url = reverse_lazy("catalog:literary_format_list")
    template_name = "catalog/literary_format_form.html"


class LiteraryFormatDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = LiteraryFormat
    success_url = reverse_lazy("catalog:literary_format_list")
    template_name = "catalog/literary_format_confirm_delete.html"


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book
    queryset = Book.objects.select_related("format")
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        title = self.request.GET.get("title", "")
        context["title"] = title
        context["search_form"] = BookSearchForm(
            initial={"title": title}
        )
        return context

    def get_queryset(self):
        # title = self.request.GET.get("title")
        # if title:
        #     return self.queryset.filter(title__icontains=title)
        # return self.queryset
        form = BookSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(title__icontains=form.cleaned_data["title"])
        return self.queryset


class BookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Book
    form_class = BookForm


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class BookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Book
    form_class = BookForm


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author
    paginate_by = 5


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class LiteraryFormatViewSet(viewsets.ModelViewSet):
    queryset = LiteraryFormat.objects.all()
    serializer_class = LiteraryFormatSerializer


class AuthorViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.all()
    serializer_class = AuthorSerializer


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

templates/catalog/author_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ author.first_name }} {{ author.last_name }}</h1>
  <div class="m-3">
    <p><strong>Books: </strong></p>
    <hr>
    {% for book in author.books.all %}
      <p class="text-muted">{{ book.id }}</p>
      <a href="{{ book.get_absolute_url }}">{{ book.title }} ({{ book.format }})</a>
      <hr>
      {% if book.description %}
        <p>{{ book.description }}</p>
      {% else %}
        <p>There is no description by this book.</p>
      {% endif %}
    {% empty %}
      <p>There are no books by this author in our library.</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/author_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Author List:</h1>
  {% if author_list %}
    <ul>
      {% for author in author_list %}
        {#        <li><a href="{% url 'catalog:book_detail' book.id %}">{{ book.title }} ({{ book.format }})</a></li>#}
        <li><a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books.</p>
  {% endif %}

{% endblock %}

templates/catalog/book_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>
  <p><strong>format: </strong>{{ book.format }}</p>
  {% if book.description %}
    <p><strong>description: </strong>{{ book.description }}</p>
  {% endif %}
  <div class="m-3">
    <h3>Authors:</h3>
    <hr>
    {% for author in book.authors.all %}
      <p class="text-muted">{{ author.id }}</p>
      <p>{{ author.first_name }} {{ author.last_name }}</p>
    {% empty %}
      <p>No authors.</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/book_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} book</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/book_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Book List:<a style="float: right" href="{% url 'catalog:book_create' %}">+</a></h1>
  <form action="" method="GET" class="form-check-inline d-flex" >
    {{ search_form|crispy }}
    <input type="submit" value="🔎" class="btn btn-outline-secondary">
  </form>
  {% if book_list %}
    <ul>
      {% for book in book_list %}
        {#        <li><a href="{% url 'catalog:book_detail' book.id %}">{{ book.title }} ({{ book.format }})</a></li>#}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }} ({{ book.format }})</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no books.</p>
  {% endif %}

{% endblock %}

templates/catalog/index.html
{% extends "base.html" %}

{% block title %}
  <title>Library homepage</title>
{% endblock %}

{% block content %}
  <h1>Welcome to the Library!</h1>
  <br>
  <h2>Library content:</h2>
  <ul>
    <li>Num books {{ num_books }}</li>
    <li>Nim authors {{ num_authors }}</li>
    <li>Num genres {{ num_literary_formats }}</li>
  </ul>

{#  <p>You have visited our site {{ num_visits }} {% if num_visits == 1 %} time {% else %} times{% endif %}</p>#}
  <p>You have visited our site {{ num_visits }} time{{ num_visits|pluralize }}</p>

{% endblock %}

templates/catalog/literary_format_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Library Format</h1>
  <p>Are you sure you want to delete the literary format: {{ literaryformat }}?</p>
  <p><i>All books with this literary format will be deleted!</i></p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete." class="btn btn-danger">
  </form>
{% endblock %}

templates/catalog/literary_format_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} literary format</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/catalog/literary_format_list.html
{#{% extends "base.html" %}#}
{##}
{#{% block content %}#}
{#  <h2>Literary format list:<a style="float: right" href="{% url 'catalog:literary_format_create' %}">+</a></h2>#}
{#  {% if literary_format_list %}#}
{#    <ul>#}
{#      {% for literary_format in literary_format_list %}#}
{#        <li>{{ literary_format.name }} ({{ literary_format.id }})</li>#}
{#      {% endfor %}#}
{#    </ul>#}
{##}
{#  {% else %}#}
{#    <p>There are no Literary formats in Library.</p>#}
{#  {% endif %}#}
{#{% endblock %}#}


{% extends "base.html" %}

{% block content %}
  <h1>Literary Format List <a style="float: right" href="{% url 'catalog:literary_format_create' %}">+</a></h1>

  {% if literary_format_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for literary_format in literary_format_list %}
        <tr>
          <td>{{ literary_format.id }}</td>
          <td>{{ literary_format.name }}</td>
          <td>{{ literary_format.description|default:"without description" }}</td>
          <td>
            <a href="{% url 'catalog:literary_format_update' pk=literary_format.id %}">UPDATE</a>
          </td>
          <td>
            <a href="{% url 'catalog:literary_format_delete' pk=literary_format.id %}">DELETE</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no literary formats in Library.</p>
  {% endif %}
{% endblock %}